name: scrumlab_flutter_tindercard
description: Tinder(TanTan) Card Widget, fast way to have a high quality swap card widget in your flutter app.
version: 1.2.0
homepage: https://github.com/scrum-lab/scrumlab_flutter_tindercard

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.2 #1.2.4

flutter:
  uses-material-design: true
